### ISSUE TITLE
🚀 RoadMap

### ISSUE THREAD

**Issue by zzhangpurdue** [modelscope/modelscope-agent#350]
## Description

This is a tentative roadmap for ModelScope-Agent, We will update it as things evolve. Some items might be discarded, others will be added later. It would be more beneficial for the community to know all the ideas and objectives.

On the other hand, answering questions, issues, and PRs is also intermixed with this file, but as in some cases one of these features would solve several issues or questions, or potentially solve something done by one or more PRs, in many cases we focus on this a bit more than on answering specific issues, questions, PRs.

## Maintenance
ModelScope-Agent is currently maintained by ModelScope team, in particular @wenmengzhou, @zzhangpurdue, @lylalala, @suluyana, @Zhikaiiii.

We also receive a lot of help from community contributors like @mushenL, @wangyijunlyy. They help answering questions, reviewing PRs, making sure things are in order and actually ready to be reviewed, etc.

We hope that with the growthing of Modescope-Agent the maintenance work could be done by the amazing community.

## Roadmap
Now, here's the current high-level tentative roadmap:

- [x] Allow Modelscope-Agent running in a distributed multi-agent mode. (Motivation: #335, Code:  #319)
- [ ] Add assistant api for user who want to modify and deploy ModelScope-Agent or [Agentfabric](https://modelscope.cn/studios/agent) on their own local system. (#342 )
- [ ] Add docker deployment file for environment control for  assistant api 
- [ ] Allow cancel and resend user query for assistant api 
- [ ] Demos for finetuning agent LLM, evaluating agent LLM and running agent llm in Modelscope-Agent(#349)
- [ ] With the increasing of tools in system, **tool retrieval** module should add back. (#340)
- [ ] Token count module, and related api for checking the token consuming. (#341)
- [ ] Skip summarization step when observation step has already generated user needed result for some tools to avoid duplicated output, and time/token consumption on user side.
- [ ] With the increasing number of tools, the api keys for the tools should be managed in one place
- [ ] RAG based on mulitple sources, such as embedding database, document database and knowledge-graph database, etc,.
- [ ] Speed up ModelScope-Agent during loading time and reduce memory consumption.
     - [ ] tool lazy load logic
     - [ ] embedding indexing module not loading on no knowledge tasks.
- [ ] Rountine Works.
     - [ ]  Add more tools
     - [ ] Support more LLM 
     - [ ] Support more Agent methods

## Note
This issue is just to keep anyone interested updated. For individual conversations, comments, requests, questions, please create a separate discussion question. Otherwise, we would end up with a single issue to cover everything and that's not the idea. 😅
